// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import DateNavigatorController from "./date_navigator_controller"
import OrgChartController from "./org_chart_controller"
import OrgDataController from "./org_data_controller"
application.register("org-chart", OrgChartController)
application.register("org-data", OrgDataController)
application.register("date-navigator", DateNavigatorController)
