// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import OrgChartController from "./org_chart_controller"
application.register("org-chart", OrgChartController)
