// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import DateSliderController from "./date_slider_controller"
import OrgChartController from "./org_chart_controller"
application.register("org-chart", OrgChartController)
application.register("date-slider", DateSliderController)
